"""README.md, filled from its template in docs/templates/readme.md.

Every number in the README is filled in here, from a warehouse query, a setting or a committed document; none is
typed into the template. During a traceability audit each is recorded as it is formatted, so `make audit` traces
every number in the README as it does those in the management pack and on the app's Overview page.

Run with `make readme`; `make pack` runs it too, so the README never lags the data. All data is synthetic.
"""

from __future__ import annotations

import re
import tomllib
from collections.abc import Callable
from pathlib import Path

import duckdb

from fabsync.design.render import PLACEHOLDER
from fabsync.pack.facts import Facts, load, md_table
from fabsync.provenance import Origin, TracedInt, quote, record, trace, word

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / "docs" / "templates" / "readme.md"
README = ROOT / "README.md"
BANNER = ("<!-- Generated by `make readme` from docs/templates/readme.md: edit the template, not this file. Every "
          "number below is filled from a warehouse query, a setting or a committed document, and `make audit` "
          "checks each one. -->\n")

QUERIES = {
    "reconciliations": "SELECT count(DISTINCT engine) FROM recon.headline",
    # Every extract's header names the seed that generated it.
    "seed": "SELECT DISTINCT regexp_extract(header_comment, 'seed (\\d+)', 1) FROM governance.source_file",
    # The date formats the shop-floor contract accepts in a single date column.
    "date_formats": "SELECT max(len(string_split(formats, ', '))) FROM governance.contract "
                    "WHERE source_system = 'shop_floor' AND declared_type = 'date'",
}
CLEAN_RUN = re.compile(r"succeeded as one command, with no manual steps, in ([\d.]+) seconds")


def query(con: duckdb.DuckDBPyConnection, name: str):
    sql = QUERIES[name]
    rows = con.execute(sql).fetchall()
    if len(rows) != 1:
        raise ValueError(f"README query {name} returned {len(rows)} rows, expected one")
    return trace(rows[0][0], "warehouse", f"query: {name}", sql)


def fields(f: Facts, con: duckdb.DuckDBPyConnection) -> dict[str, Callable[[], str]]:
    """How each placeholder is filled. Each is called once per use, so every number printed is recorded."""
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    app = tomllib.loads((ROOT / ".streamlit" / "config.toml").read_text(encoding="utf-8"))
    progress = CLEAN_RUN.search((ROOT / "docs" / "progress.md").read_text(encoding="utf-8"))
    if not progress:
        raise ValueError("docs/progress.md no longer records the clean run from a fresh clone")
    defects = md_table((ROOT / "docs" / "project-brief.md").read_text(encoding="utf-8"), "| # | Defect | Where |")
    assumptions = f.benefits["assumptions"]
    weights = f.severity_weights

    def extract_date() -> str:
        text = f"{f.as_of:%-d %B %Y}"
        record(text, Origin("warehouse", "extract date", "SELECT as_of_date FROM marts.parameters"))
        return text

    def count(n: int, kind: str, name: str, detail: str = "") -> TracedInt:
        return TracedInt(n, Origin(kind, name, detail))

    return {
        "systems": lambda: word(f.systems),
        "sites": lambda: word(f.source["sites"]),
        "site_names": lambda: " and ".join(f.sites.values()),
        "rules": lambda: f"{f.dq['rules_run']:.0f}",
        "reconciliations": lambda: word(query(con, "reconciliations")),
        "kpis": lambda: word(f.kpi_count),
        "example_job_code": lambda: f"{f.fig['example_job_code']:.0f}",
        "python": lambda: quote(project["requires-python"].lstrip(">="), "config", "pyproject.toml requires-python",
                                project["requires-python"]),
        "port": lambda: quote(str(app["server"]["port"]), "config", ".streamlit/config.toml server.port",
                              str(app["server"]["port"])),
        "clean_run": lambda: quote(progress.group(1), "document", "docs/progress.md, clean run from a fresh clone"),
        "seed": lambda: f"{query(con, 'seed'):.0f}",
        "months": lambda: f"{f.source['months']:.0f}",
        "extract_date": extract_date,
        "files": lambda: f"{f.source['files']:.0f}",
        "date_formats": lambda: word(query(con, "date_formats")),
        "exc3_jobs": lambda: f"{f.fig['exc3_jobs']:.0f}",
        "exc2_jobs": lambda: f"{f.fig['exc2_jobs']:.0f}",
        "defects": lambda: f"{count(len(defects), 'document', 'docs/project-brief.md, table of registered defects')}",
        "raw_rows_rounded": lambda: f"{round(f.source['raw_rows'], -3):,.0f}",
        "qty_tolerance": lambda: f"{f.reconcile['three_way']['qty_tolerance']:.0%}",
        "price_tolerance": lambda: f"{f.reconcile['three_way']['price_tolerance_pct']:.0%}",
        "stock_target": lambda: f"{f.reconcile['stock']['accuracy_target']:.0%}",
        "w_critical": lambda: f"{weights['critical']:.0f}",
        "w_high": lambda: f"{weights['high']:.0f}",
        "w_medium": lambda: f"{weights['medium']:.0f}",
        "w_low": lambda: f"{weights['low']:.0f}",
        "assumptions": lambda: word(count(len(assumptions), "document", "benefits case assumptions",
                                          "docs/benefits-case.md, Assumptions")),
        "first_assumption": lambda: assumptions[0][0],
        "last_assumption": lambda: assumptions[-1][0],
        "phases": lambda: word(count(len(f.roadmap["phases"]), "config", "roadmap.yaml number of phases")),
        "plan_months": lambda: f"{f.months}",
        "risks": lambda: f"{count(len(f.roadmap['risks']), 'config', 'roadmap.yaml number of risks')}",
    }


def render(f: Facts, con: duckdb.DuckDBPyConnection) -> str:
    """The README, with every placeholder filled in the order it appears."""
    template = TEMPLATE.read_text(encoding="utf-8")
    fill = fields(f, con)
    unknown = sorted(set(PLACEHOLDER.findall(template)) - set(fill))
    if unknown:
        raise ValueError(f"unknown README fields: {', '.join(unknown)}")
    return BANNER + PLACEHOLDER.sub(lambda m: fill[m.group(1)](), template)


def build(warehouse: Path) -> str:
    con = duckdb.connect(str(warehouse), read_only=True)
    try:
        return render(load(con), con)
    finally:
        con.close()


def main() -> None:
    README.write_text(build(ROOT / "data" / "warehouse" / "fabsync.duckdb"), encoding="utf-8")
    print("README.md written from docs/templates/readme.md (synthetic data)")


if __name__ == "__main__":
    main()
