"""docs/data-dictionary.md and docs/kpi-report.md.

The dictionary is one table, one row per KPI, laid out to be lifted straight
into the PDF pack. The report shows current values, and never a value without
its caveat. Neither holds run ids or timestamps.
"""

from __future__ import annotations

import pandas as pd


def md(v) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    return " ".join(str(v).split()).replace("|", "\\|")


def fmt(value, unit: str | None) -> str:
    if value is None or pd.isna(value):
        return "no data"
    if unit == "GBP":
        return f"£{value:,.0f}"
    if unit == "percent":
        return f"{value:.1f}%"
    return f"{value:,.2f}".rstrip("0").rstrip(".")


def frame_table(frame: pd.DataFrame, cols: list[str] | None = None, heads: list[str] | None = None) -> list[str]:
    cols = cols or list(frame.columns)
    heads = heads or [c.replace("_", " ").replace(" pct", " %").capitalize() for c in cols]
    out = ["| " + " | ".join(heads) + " |", "|" + "|".join(" --- " for _ in heads) + "|"]
    for r in frame[cols].itertuples(index=False):
        cells = []
        for v in r:
            if isinstance(v, bool):
                cells.append("yes" if v else "no")
            elif isinstance(v, float) and not pd.isna(v):
                cells.append(f"{v:,.2f}".rstrip("0").rstrip("."))
            elif isinstance(v, int):
                cells.append(f"{v:,}")
            else:
                cells.append(md(v))
        out.append("| " + " | ".join(cells) + " |")
    return out


def render_dictionary(definitions: pd.DataFrame, views: pd.DataFrame, params: dict) -> str:
    out = [
        "# Data dictionary: KPIs",
        "",
        "**All data behind these KPIs is synthetic.** It represents no real company, supplier, customer or job.",
        "",
        "Generated by `make kpi` from `config/kpis.yaml`. Each KPI is a documented SQL view in the `marts` schema;",
        "`marts.kpi_definition` holds these records and `marts.kpi_scorecard` the current values. The caveat is",
        "part of the definition: a KPI shown without its limitations is how dashboards lose trust.",
        "",
        "## KPI definitions",
        "",
        "| ID | KPI | Definition | Formula | Sources and systems | Owner | Refresh | Target | Caveat |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in definitions.itertuples():
        out.append(f"| {r.kpi_id} | {md(r.name)} | {md(r.definition)} | {md(r.formula)} | {md(r.sources)} | "
                   f"{md(r.owner)} | {md(r.refresh)} | {md(r.target)} | {md(r.caveat)} |")
    out += [
        "",
        "## Views",
        "",
        "Every object in the `marts` schema, with the description stored against it in the warehouse.",
        "",
        "| View | KPI | Description |",
        "| --- | --- | --- |",
    ]
    for r in views.sort_values(["kpi_id", "view"]).itertuples():
        out.append(f"| `{r.view}` | {r.kpi_id} | {md(r.description)} |")
    out += [
        "",
        "## Settings the views use",
        "",
        "| Setting | Value | Source |",
        "| --- | --- | --- |",
        f"| As-of date | {params['as_of_date']} | `config/reconcile.toml` |",
        f"| Standard labour rate | £{params['labour_rate']:.2f} per hour | `config/reconcile.toml` |",
        f"| Despatch matching window | {params['despatch_window_days']} days after works order finish | "
        "`config/reconcile.toml` |",
        f"| Stock bar length | {params['bar_length_mm'] / 1000:g} m | `config/kpis.yaml` |",
        f"| Stock accuracy target | {params['stock_accuracy_target_pct']:g}% | `config/reconcile.toml` |",
        "",
    ]
    return "\n".join(out)


def render_kpi_report(scorecard: pd.DataFrame, definitions: pd.DataFrame, breakdowns: dict[str, pd.DataFrame],
                      params: dict) -> str:
    defs = definitions.set_index("kpi_id")
    out = [
        "# KPI report",
        "",
        "**All data behind these KPIs is synthetic.** It represents no real company, supplier, customer or job.",
        "",
        f"As at {params['as_of_date']}. Definitions, formulas and sources are in `docs/data-dictionary.md`. Every "
        "figure is shown with its caveat.",
        "",
        "## Scorecard",
        "",
        "| KPI | Value | Target | Status | Also | Owner |",
        "| --- | ---: | --- | --- | --- | --- |",
    ]
    for r in scorecard.itertuples():
        also = f"{r.secondary_label}: {fmt(r.secondary_value, r.secondary_unit)}" if isinstance(
            r.secondary_label, str) else ""
        out.append(f"| {r.kpi_id} {md(r.name)} | **{fmt(r.value, r.unit)}** | {md(r.target)} | {r.status} | "
                   f"{md(also)} | {r.owner} |")
    sections = {
        "KPI-01": [("By site", "otif_by_site", None), ("Five customers with the lowest OTIF (five or more "
                                                        "deliveries measured)", "otif_by_customer", None)],
        "KPI-02": [("Five jobs with the largest variance on completed works", "labour_by_job", None)],
        "KPI-03": [("By section type", "yield", ["section_type", "cut_yield_pct", "offcut_waste_pct", "issued_kg",
                                                  "received_kg", "received_to_issued"])],
        "KPI-04": [("By site", "stock", ["site_code", "counted_lines", "accurate_lines", "accuracy_pct",
                                          "meets_target", "value_error"])],
        "KPI-05": [("Value at risk by category", "three_way", None)],
        "KPI-06": [("By site", "trace_by_site", None)],
        "KPI-07": [("Ageing", "wip", None)],
        "KPI-08": [("By site", "capacity", None)],
        "KPI-09": [("By NCR category", "ncr", None)],
    }
    for r in scorecard.itertuples():
        d = defs.loc[r.kpi_id]
        against = "No target is set; for information." if r.target == "no target" else (
            f"Target {r.target}: {r.status}.")
        out += ["", f"## {r.kpi_id} {r.name}", "",
                f"**{fmt(r.value, r.unit)}**. {against}"
                + (f" {r.secondary_label}: {fmt(r.secondary_value, r.secondary_unit)}." if isinstance(
                    r.secondary_label, str) else ""),
                "", md(d.definition), "", f"> **Caveat.** {md(d.caveat)}"]
        for title, key, cols in sections.get(r.kpi_id, []):
            out += ["", f"{title}:", "", *frame_table(breakdowns[key], cols)]
    out.append("")
    return "\n".join(out)
